# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/rogue-agent/NeXTechMC/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="nextech" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="NexTech" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/nxtsel3" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="ico.png" #optional
# A text field displayed in the mod UI
credits="Thanks to KingNXT, Choonster, Jimbo, Wuppy and all the others not mentioned for helping us out, also airwolf for nice reviews!" #optional
# A text field displayed in the mod UI
authors="Rogue-Agent and Wooden3 Studios' NexTech dev team" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
NeXTech, but why?
You may Use the addons for better experience. The Computers addon will
give you better looking computers and laptops ingame, they are like CCraft
computers with better moddeling and textures. Bloons Tech addon brings more High tech to the game.

There are many new addons coming, like the advanced crafting; automated, bigger craftting grid and much more.

Every texture should be 32x32 for more pixels. Replace your old rusty IC2 machines with the brand new Machines with Power.

And Not that expensiv! Every block/item/ore is like in real life.
'''

